### ISSUE TITLE
Unclickable button over an option card

### ISSUE THREAD

**Issue by AudranL** [adeo/mozaic-design-system#1318]
### I am opening an issue for

Styles (CSS, SCSS, ...)

### Package version

@mozaic-ds/styles@1.50.1

### Description

Since the update of @mozaic-ds/styles from 1.49.1 to 1.50.1 we cannot click on the "Continuer" button that you can see on the screenshot below.
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/91188510/210354268-047f791d-9752-4664-a133-ae034083cc5a.png">

I think that is due to the usage of the z-index in the _c.option-card.scss style file that was added in v1.50.1 that you can see on the screenshot below.
![image](https://user-images.githubusercontent.com/91188510/210354960-65810c04-6323-45ff-b996-e1ca91f53501.png)

We have to rollback on V1.49.1

### GitHub repository

https://github.com/adeo/configurators--front-door

### Is this a regression?

- [ ] Yes
- [ ] No
- [ ] I don't know

**Comment by tiloyi** [comment]
Hi @AudranL ,
Thank you for your issue.

As we saw together during our Meet, last time; we made an evolution in the component so as to [reduce the value of our z-indexes](https://github.com/adeo/mozaic-design-system/pull/1319/files).

However, as we discussed, you will need to increase the z-index value of your bottom bar, the one containing the "Continue" button, so that things balance out.

I'm at your disposal if you need me,
