### ISSUE TITLE
fix(Heading)

### ISSUE THREAD

**Issue by gaelHugotLm** [adeo/mozaic-design-system#507]
Hi there,

About `.mt-heading` default class, we have a `display: block;` value, it was really necessary ?

By default, `display ` default value is `block`,, can we give to user (us) the possibility to set this property himself to avoid squashed properties ?

**Comment by tiloyi** [comment]
Hello @gaelHugotLm 
The styles of the typographies on Mozaic are designed to work on an element independently of the tag on which they are applied. 

As a result, it is possible that the `.mt-heading` class may be applied to an inline HTML element, such as a `span` for example (this is at the discretion of the developer).

Therefore, to ensure the good behavior and the good rendering of the pattern, the `display: block` property is necessary for cases where the class would be applied on an "inline" HTML element.

As you know, since most HTML elements are block elements (but implicitly), it seems to me that you won't need to override this rule (unless you have a concrete example to give?).
