### ISSUE TITLE
flag bug regarding the text

### ISSUE THREAD

**Issue by marineFabien** [adeo/mozaic-design-system#669]
# 🐞 Styleguide bug report

### Is this a regression?

No

### Description

If you put a flag component inside an element that is positioned as display: flex, the flag behaves weird, you can see it below with the example picture.

the problem is resolved when we delete the `height:0;`  which is on `mc-flag` class

## 📷 Screenshot
![flag](https://user-images.githubusercontent.com/49992054/98274527-d0488800-1f93-11eb-8d2d-b510f8ad50cd.PNG)

![code](https://user-images.githubusercontent.com/49992054/98274659-fb32dc00-1f93-11eb-8990-4051b4a38c63.PNG)

**Comment by tiloyi** [comment]
Hi @marineFabien ,
Thank you for reporting this problem and for suggesting a solution.

However, we can't remove the `height: 0;` rule because the default behavior of a flag is that it always stays on one line. 

Therefore, in order to preserve the integrity of the component, but also to respond to the problem, I have just made an evolution that consists of two things: 

1. change the `flex-shrink` property of the flag component, so that it can't shrink when the parent has a `display: flex` (as in your example)
2. provide a `mc-flag--extend` modifier that allows to use a multi-line flag in a very exceptional way.

I hope this will solve your problem.
++

**Comment by marineFabien** [comment]
Thanks a lot, i can't wait for testing it soon ;)
