### ISSUE TITLE
New versions seems not to be available on npm repositories

### ISSUE THREAD

**Issue by Tony-Proum** [adeo/mozaic-design-system#733]
trying to intall new versions following the [documentation](https://mozaic.adeo.cloud/GetStarted/Developers/Installation/) , I were not able to find the 1.3.0. 

e.g: 
https://www.npmjs.com/package/@mozaic-ds/css-dev-tools
https://preview.npmjs.com/package/@mozaic-ds/postcss-media-queries-packer-on-demand?activeTab=readme

**Comment by tiloyi** [comment]
Hi @Tony-Proum ,
Thank you for your message.

In fact, the version of the packages you just indicated, only changes if modifications are made inside.

These packages have not been modified since version 1.0.1, so the version number has not increased following the main package (@mozaic-ds/styles) version.

As a result, version 1.0.1 is the latest version of these packages. :)

I hope I was able to answer your question,
I remain at your disposal
