### ISSUE TITLE
Cannot customize the stylelint rules

### ISSUE THREAD

**Issue by potpot59** [adeo/mozaic-design-system#791]
# 🐞 Pattern bug report

### Where did you experience this bug ?
	
- [ ] On sketch file
- [x] On Documentation
- [ ] On source code

### Is this a regression?

 I don't know

### Description

 I tried to customize the stylelint rules as explained in the doc here: https://mozaic.adeo.cloud/GetStarted/Developers/Installation/stylelint/
But it seems ignored.
You can view the file here: https://github.com/adeo/tempo-order-admin/blob/master/tempo-order-admin-front/stylelint.config.js

## 🌍 Your Environment

    "@mozaic-ds/css-dev-tools": "^1.6.1",
    "@mozaic-ds/icons": "^1.0.1",
    "@mozaic-ds/styles": "^1.6.2",
    "@mozaic-ds/tokens": "^1.4.0",
    "@mozaic-ds/web-fonts": "^1.0.1",

**Comment by tiloyi** [comment]
Hi @potpot59 ,
Thanks for your issue.

I have looked into the problem in detail and it turns out that **Stylelint** is not able to read the `stylelint.config.js` file, with the **PostCSS** configuration that we have.

So, the solution to your problem would be to remove **Stylelint** from the list of plugins we provide. Then add it directly to your code.

It would look like this:

```javascript
// vue.config.js

const stylelint = require('stylelint');
const mozaicRules = require('@mozaic-ds/css-dev-tools/styleLintConfig.js');
let pluginList = require('@mozaic-ds/css-dev-tools/postcssPluginConfig');

pluginList = pluginList.filter(({ postcssPlugin }) => postcssPlugin !== 'stylelint');
pluginList.unshift(stylelint({ configOverrides: mozaicRules }));
```

So your `stylelint.config.js` file would become:

```javascript
// stylelint.config.js

"use strict";

const customRules = {
  "selector-pseudo-element-no-unknown": [
    true,
    {
      ignorePseudoElements: ["v-deep"]
    }
  ]
};

module.exports = {
  rules: customRules
};
```

I have created the following PR (https://github.com/adeo/tempo-order-admin/pull/863) that allows you to test and if it is OK for you to merge it in your project.

Let me know if it's good for you.

**Comment by potpot59** [comment]
Perfect, it works well.
Thanks you
