### ISSUE TITLE
Transparency on MCLayer

### ISSUE THREAD

**Issue by fgruchala** [adeo/mozaic-design-system#909]
# 🐞 Transparency on MCLayer

### Where did you experience this bug ?
	
- [ ] On sketch file
- [ ] On Documentation
- [x] On source code

### Description

As a first analysis, on the CSS class `.mc-layer__body--overflowing**`, it seems that we have a shadow from black/grey to a transparent, it's good but this shadow is not in front of the content, so we have a not verry fully transparent shadow.

Is it possible ?

## 📷 Screenshot

<img width="1680" alt="Capture d’écran 2021-09-07 à 15 21 40" src="https://user-images.githubusercontent.com/12196721/132354509-a854f43d-203c-47cf-9d55-d7d17816d9ed.png">

**Comment by fgruchala** [comment]
Little UP @mohamedMok @tiloyi

**Comment by tiloyi** [comment]
Hi @fgruchala ,
As seen together, it seems that the problem is that there is a CSS overides of the Layer component code in your project.
Specifically the addition of a `padding-bottom` on the `.mc-layer__body` element.

After investigation, the overides are in the following file in your project => `frontend/src/components/m-layer/MLayer.vue`

By removing the overides, you won't have the problem anymore :)
